services:
  mongodb:
    container_name: mongodb-wichat_es2c
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    restart: always

  authservice:
    container_name: authservice-wichat_es2c
    image: ghcr.io/arquisoft/wichat_es2c/authservice:latest
    profiles: ["dev", "prod"]
    build: ./users/authservice
    depends_on:
      - mongodb
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  userservice:
    container_name: userservice-wichat_es2c
    image: ghcr.io/arquisoft/wichat_es2c/userservice:latest
    profiles: ["dev", "prod"]
    build: ./users/userservice
    depends_on:
      - mongodb
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  userinfoapi:
    container_name: userinfoapi-wichat_es2c
    image: ghcr.io/arquisoft/wichat_es2c/userinfoapi:latest
    profiles: ["dev", "prod"]
    build: ./users/userinfoapi
    depends_on:
      - mongodb
    ports:
      - "8005:8005"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  llmservice:
    container_name: llmservice-wichat_es2c
    image: ghcr.io/arquisoft/wichat_es2c/llmservice:latest
    profiles: ["dev", "prod"]
    build: ./llmservice
    ports:
      - "8003:8003"
    networks:
      - mynetwork

  gatewayservice:
    container_name: gatewayservice-wichat_es2c
    image: ghcr.io/arquisoft/wichat_es2c/gatewayservice:latest
    profiles: ["dev", "prod"]
    build: ./gatewayservice
    depends_on:
      - mongodb
      - userservice
      - authservice
      - llmservice
      - game
      - wikidata
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      AUTH_SERVICE_URL: http://authservice:8002
      USER_SERVICE_URL: http://userservice:8001
      LLM_SERVICE_URL: http://llmservice:8003
      GAME_SERVICE_URL: http://game:8004
      WIKIDATA_SERVICE_URL: http://wikidata:3005

  webapp:
    container_name: webapp-wichat_es2c
    image: ghcr.io/arquisoft/wichat_es2c/webapp:latest
    profiles: ["dev", "prod"]
    build: 
      context: ./webapp
      args:
        LLM_API_KEY: ${LLM_API_KEY}
    depends_on:
      - gatewayservice
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    container_name: prometheus-wichat_es2c
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - gatewayservice
      
  grafana:
    image: grafana/grafana
    container_name: grafana-wichat_es2c
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - prometheus

  game:
    container_name: game-wichat_es2c
    image: ghcr.io/arquisoft/wichat_es2c/game:latest
    profiles: ["dev", "prod"]
    build: ./game
    depends_on:
      - mongodb
    ports:
      - "8004:8004"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  wikidata:
    container_name: wikidata-wichat_es2c
    image: ghcr.io/arquisoft/wichat_es2c/wikidata:latest
    profiles: [ "dev", "prod" ]
    build: ./wikidata
    depends_on:
      - mongodb
    ports:
      - "3005:3005"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb


volumes:
  mongodb_data:
  prometheus_data: 
  grafana_data: 

networks:
  mynetwork:
    driver: bridge
