ifndef::imagesdir[:imagesdir: ../images]

[[section-design-decisions]]
== Architecture Decisions

The application will be carried out following a Microservices architecture. +

The service in charge of comunicating with WikiData will be coded using TypeSript. 
As the generation of questions is a huge part of our application we will play it safe by using TypeSript, a language that is similar to JavaSript but with static type checking.

*03/02/2025*

The backend will we use Node and React for the fronend.

For the database, we have chosen MongoDB, which is a non-relational database.

To deploy the application, we will use a server owned by one of the team members.

*03/03/2025*

We have decided to switch from using TypeScript to JavaScript due to issues when working with it. Initially, we thought it would help us write more readable code since TypeScript is JavaScript with static typing, but in the end, we will use JavaScript.

We have decided to use CSS Modules because it prevents style collisions, is more organized, and easier to maintain.


[role="arc42help"]


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationales.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. 
Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* ADR (https://cognitect.com/blog/2011/11/15/documenting-architecture-decisions[Documenting Architecture Decisions]) for every important decision
* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision

.Further Information

See https://docs.arc42.org/section-9/[Architecture Decisions] in the arc42 documentation.
There you will find links and examples about ADR.

****
endif::arc42help[]
