openapi: 3.0.0
info:
  title: UserInfo API
  description: API to manage user information
  version: 1.0.0
  contact:
    email: uo294381@uniovi.es
servers:
  - url: http://localhost:8005
    description: Server for API
paths:
  /userinfo:
    get:
      summary: Get information about all users
      description: Returns an array with information of all registered users, excluding their passwords
      operationId: getAllUsers
      responses:
        '200':
          description: List of users successfully retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /userinfo/{username}:
    get:
      summary: Get information about a specific user
      description: Returns information of a specific user by their username, excluding their password
      operationId: getUserByUsername
      parameters:
        - name: username
          in: path
          required: true
          description: Username to search for
          schema:
            type: string
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          description: Unique user ID in MongoDB
        username:
          type: string
          description: Unique username
        createdAt:
          type: string
          format: date-time
          description: Date when the user was created
      required:
        - _id
        - username
        - createdAt
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
      required:
        - error